@startuml
'https://plantuml.com/class-diagram

abstract class EnemyFactory {
    + {abstract} creatEnemy():AbstractAircraft
}

class MobFactory {
    + creatEnemy():AbstractAircraft
}

class EliteFactory {
    + creatEnemy():AbstractAircraft
}

class BossFactory {
    + creatEnemy():AbstractAircraft
}

class Game {
}

abstract class AbstractFlyingObject
{
    # locationX:int
    # locationY:int
    # speedX:int
    # speedY:int
    # image:BufferedImage
    # width:int
    # height:int
    # isValid:boolean

    + AbstractFlyingObject(int locationX, int locationY, int speedX, int speedY)
    + forward():void
    + crash(AbstractFlyingObject flyingObject):boolean
    + setLocation(double locationX, double locationY):void
    + getLocationX():int
    + getLocationY():int
    + getSpeedY():int
    + getImage():BufferedImage
    + getWidth():int
    + getHeight():int
    + notValid():boolean
    + vanish():void
}

abstract class AbstractAircraft
{
	# maxHp:int
    # hp:int
    + AbstractAircraft(int locationX, int locationY, int speedX, int speedY, int hp)
    + decreaseHp(int decrease):void
    + getHp():int
    + {abstract} shoot():List<AbstractBullet>
}

class MobEnemy {
    + MobEnemy(int locationX, int locationY, int speedX, int speedY, int hp)
    + forward():void
    + shoot():List<AbstractBullet>
}

class EliteEnemy {
    - shootNum:int
    - power:int
    - direction:int
    + EliteEnemy(int locationX, int locationY, int speedX, int speedY, int hp)
    + forward():void
    + shoot():List<AbstractBullet>
}

class Boss {
    - shootNum:int
    - power:int
    - direction:int
    + Boss(int locationX, int locationY, int speedX, int speedY, int hp)
    + forward():void
    + shoot():List<AbstractBullet>
}

AbstractFlyingObject <|-- AbstractAircraft

AbstractAircraft <|-- MobEnemy
AbstractAircraft <|-- EliteEnemy
AbstractAircraft <|-- Boss

EnemyFactory <|-- MobFactory
EnemyFactory <|-- EliteFactory
EnemyFactory <|-- BossFactory

Game ..> EnemyFactory
Game ..> AbstractAircraft

MobFactory ..> MobEnemy
EliteFactory ..> EliteEnemy
BossFactory ..> Boss

@enduml